"""create media and media_records tables

Revision ID: f9645b12adca
Revises:
Create Date: 2026-08-14 20:57:48.128754

"""  # noqa: N999

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9645b12adca"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum("TELEGRAM", "NEWSPAPER", name="mediatype", create_constraint=True),
            nullable=False,
        ),
        sa.Column("media_name", sa.String(), nullable=False),
        sa.Column("reputation", sa.Float(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
        sa.UniqueConstraint(
            "media_type",
            "media_name",
            name=op.f("uq_media_media_type"),
        ),
    )
    op.create_table(
        "media_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("added_by", sa.UUID(), nullable=False),
        sa.Column("posted_in_media", sa.UUID(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["posted_in_media"],
            ["media.id"],
            name=op.f("fk_media_records_posted_in_media_media"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_records")),
    )
    op.create_index(
        op.f("ix_media_records_posted_in_media"),
        "media_records",
        ["posted_in_media"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_records_posted_in_media"), table_name="media_records")
    op.drop_table("media_records")
    op.drop_table("media")
    # ### end Alembic commands ###
